# Generated by Django 5.0.7 on 2024-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsarticle_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='language',
            field=models.CharField(blank=True, choices=[('КР', 'кыргыз тили'), ('RU', 'Русский язык')], default='RU', max_length=255, null=True, verbose_name='Язык'),
        ),
    ]
